Repository Rutuj-Runwal/easynotes, pull requests merged in 2022-10, with the labels that each got.

#2 Added Product Image
  assests/demo_1.png
  assests/demo_2.png
Labels: hacktoberfest2022, hacktoberfest-accepted

#5 Readme and Documentation Update
  README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#7 feat: added gitignore file
  .gitignore
Labels: documentation, hacktoberfest2022, hacktoberfest-accepted
